version: '3.3'

services:
  makobot:
    restart: unless-stopped
    image: dynamicsamic/bday_bot:v0.7
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - ./.env
    volumes:
      - bot_data:/makobot/data

volumes:
  bot_data:
